config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :favorites, only: [:create, :destroy, :show]
  root to: 'sessions#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @favorites = current_user.favorites.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = current_user.pictures.build
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      ContactMailer.contact_mail(@picture).deliver
      redirect_to @picture, notice: 'Picture page was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture page was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def ensure_correct_user
    @picture = Picture.find(params[:id])
    if @picture.user_id != current_user.id
      flash[:notice] = "No authority"
      redirect_to pictures_url
    end
  end

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'
        confirm_pictures_path
    elsif action_name == 'edit'
        picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/favorites/show.html.erb
<h1><%= @user.name %>のお気に入り一覧</h1>
<table>
<% @favorites.each do |favorite| %>
  <tbody>
    <tr>
      <td><%= favorite.user.name %></td>
    </tr>
    <tr>
      <td><%= favorite.picture.content %></td>
    </tr>
    <tr>
      <td><%= image_tag(favorite.picture.image.url) %></td>
    </tr>
  </tbody>
  <tfooter>
    <tr>
      <td><%= link_to 'お気に入り解除する', favorite_path(id: favorite.id), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  </tfooter>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container-fluid">
      <h1 id="head_title">Instagram Clone</h1>
      <% if logged_in? %>
        <ul class="row">
          <li class="col-md-2"><%= link_to 'Home', pictures_path %></li>
          <li class="col-md-2"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="col-md-2"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <li><p>ユーザー名: <%= current_user.name %></p></li>
        </ul>
      <% else %>
        <ul class="row">
          <li class="col-md-2"><%= link_to "Sign up", new_user_path %></li>
          <li class="col-md-2 col-md-offset-8"><%= link_to "Login", new_session_path %></li>
        </ul>
      <% end %>
    </header>

    <div class="content_area">
      <div class="notification">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
      <%= yield %>
    </div>

    <footer class="footer">
      <p>Copyright © 2021 teramoto ALL RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input_area">
    <%= form.label :content %>
    <%= form.text_area :content, placeholder: "What are you doing?" %>

    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <br>
    <%= form.submit 'create new post', class: 'button' %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<br>
<h3 id="message">以下の内容でツイートする。</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <p>User: <%= @picture.user.name %></p>
  <%= form.hidden_field :content %>
  <p>Content: <%= @picture.content %></p>
  <%= form.hidden_field :image_cache %>
  <p>Image: <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
  <%= form.submit "Post" %>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Back", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>
<%= render 'form', picture: @picture %>
<br><br><br>
<br><br><br>
<br><br><br>
<div class="link_button1">
  <%= link_to 'Show', @picture %>
  <br>
  <%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/index.html.erb
<h1>Home</h1>

<div class="picture_content">

  <table>
    <% @pictures.each do |picture| %>

      <tbody>
        <tr>
          <td><%= picture.user.name %></td>
        </tr>
        <tr>
          <td><%= picture.content %></td>
        </tr>
        <tr>
          <td><%= image_tag(picture.image.to_s) %></td>
        </tr>
      </tbody>

      <tfooter>
        <tr>
          <td>
            <%= link_to 'Show', picture %>
            <% if picture.user.id == current_user.id %>
              <%= link_to 'Edit', edit_picture_path(picture) %>
              <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      </tfooter>

    <% end %>
  </table>
</div>

<%= link_to '投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Post</h1>

<%= render 'form', picture: @picture %>
<div class="link_button1">
  <%= link_to 'back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@picture.image.url) %>
</p>

<div class="link_button1">
  <%= link_to 'Edit', edit_picture_path(@picture) %>
  <%= link_to 'Home', pictures_path %>
  <br>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りにする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="input_area">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "your user name" %>
    <%= f.label :profile_image %>
    <%= f.file_field :image, id: :user_image %>
    <%= f.hidden_field :image_cache %>
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "your email" %>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "type same password" %>
    <br>
    <%= f.submit yield(:button_text), class: 'button' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, 'Save changes')%>
<h1>Update profile</h1>
<%= render 'form' %>
<div class="link_button2">
  <%= link_to 'Unchange profile', user_path(current_user.id) %>
</div>

app/views/users/new.html.erb
<% provide(:button_text, 'Create new account')%>
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>
  プロフィール画像：
  <% if @user.image? %>
    <%= image_tag @user.image.url %>
  <% end %>
</p>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to 'Post', new_picture_path %>
<br>
<%= link_to 'プロフィールの編集', edit_user_path(current_user.id)%>
<br>
<%= link_to 'お気に入り一覧', favorite_path(current_user.id)%>